apiVersion: iam.services.k8s.aws/v1alpha1
kind: Role
metadata:
  name: ack-image-resizer-role
spec:
  name: ack-image-resizer-role
  description: 'IAM role for ack-image-resizer applications'
  maxSessionDuration: 3600 # fix docs to specify it in seconds
  assumeRolePolicyDocument: '{"Version":"2012-10-17","Statement":[{"Effect":"Allow","Principal":{"Service":["lambda.amazonaws.com"]},"Action":["sts:AssumeRole"]}]}'
  policies:
  - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
  - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
  - arn:aws:iam::aws:policy/AWSLambda_ReadOnlyAccess
  - arn:aws:iam::aws:policy/AWSXrayWriteOnlyAccess
  - arn:aws:iam::aws:policy/AmazonS3FullAccess
  tags:
    - key: application
      value: ack-image-resizer