AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Lambda application that calls the Lambda API.
Resources:
  bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
  function:
    Type: AWS::Serverless::Function
    Properties:
      ImageUri: 481121494044.dkr.ecr.eu-west-1.amazonaws.com/ack-image-resizer
      PackageType: Image
      Handler: example.Handler
      Runtime: java8
      Description: Java function
      MemorySize: 512
      Timeout: 10
      Policies:
      - AWSLambdaBasicExecutionRole
      - AWSLambda_ReadOnlyAccess
      - AWSXrayWriteOnlyAccess
      - AWSLambdaVPCAccessExecutionRole
      - AmazonS3FullAccess
      Tracing: Active
      Layers:
      - Ref: libs
      Events:
        s3Notification:
          Type: S3
          Properties:
            Bucket:
              Ref: bucket
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                - Name: prefix
                  Value: inbound/
      CodeUri: s3://image-resizer-lambda-artifacts/77b1962ca8932b42894f5862ba14d813
