// generated by cdk8s
import { ApiObject, ApiObjectMetadata, GroupVersionKind } from 'cdk8s';
import { Construct } from 'constructs';


/**
 *
 *
 * @schema ENIConfig
 */
export class EniConfig extends ApiObject {
  /**
   * Returns the apiVersion and kind for "ENIConfig"
   */
  public static readonly GVK: GroupVersionKind = {
    apiVersion: 'crd.k8s.amazonaws.com/v1alpha1',
    kind: 'ENIConfig',
  }

  /**
   * Renders a Kubernetes manifest for "ENIConfig".
   *
   * This can be used to inline resource manifests inside other objects (e.g. as templates).
   *
   * @param props initialization props
   */
  public static manifest(props: EniConfigProps = {}): any {
    return {
      ...EniConfig.GVK,
      ...toJson_EniConfigProps(props),
    };
  }

  /**
   * Defines a "ENIConfig" API object
   * @param scope the scope in which to define this object
   * @param id a scope-local name for the object
   * @param props initialization props
   */
  public constructor(scope: Construct, id: string, props: EniConfigProps = {}) {
    super(scope, id, {
      ...EniConfig.GVK,
      ...props,
    });
  }

  /**
   * Renders the object to Kubernetes JSON.
   */
  public toJson(): any {
    const resolved = super.toJson();

    return {
      ...EniConfig.GVK,
      ...toJson_EniConfigProps(resolved),
    };
  }
}

/**
 * @schema ENIConfig
 */
export interface EniConfigProps {
  /**
   * @schema ENIConfig#metadata
   */
  readonly metadata?: ApiObjectMetadata;

}

/**
 * Converts an object of type 'EniConfigProps' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_EniConfigProps(obj: EniConfigProps | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'metadata': obj.metadata,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

